/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
	public static void main(String[] args)
	{
		int[][] a = {
			{1,2,3},
			{4,5,6},
			{1,3,5}
		};
		System.out.println(sum2D(a)); //should print 30
	}
	
	public static int sum2D(int[][] nums){
		int sum = 0;
		for(int row = 0; row < nums.length; row++){
			for(int col = 0; col < nums[0].length; col++){
				sum += nums[row][col];
			}
		}
		return sum;
	}
}
